# Generated by Django 4.1.7 on 2026-05-18 07:51

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):
    dependencies = [
        ("app", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="event",
            name="capacity",
        ),
        migrations.RemoveField(
            model_name="event",
            name="date",
        ),
        migrations.RemoveField(
            model_name="event",
            name="organizer",
        ),
        migrations.AddField(
            model_name="event",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True, default=django.utils.timezone.now
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="event",
            name="end_time",
            field=models.DateTimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="event",
            name="start_time",
            field=models.DateTimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="event",
            name="location",
            field=models.CharField(max_length=255),
        ),
    ]
