# Generated by Django 4.1.7 on 2026-05-18 08:32

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("app", "0002_remove_event_capacity_remove_event_date_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="event",
            name="tickets_sold",
            field=models.PositiveIntegerField(default=0),
        ),
    ]
